### ISSUE TITLE
Where is the nest-layout-card?

### ISSUE THREAD

**Issue by marrobHD** [isabellaalstrom/home-assistant-config#2]
Where is the nest-layout-card? I cant find it

**Comment by michaelarnauts** [comment]
https://github.com/isabellaalstrom/home-assistant-config/blob/master/lovelace/102_nest_dashboard.yaml

**Comment by Misiu** [comment]
https://github.com/isabellaalstrom/home-assistant-config/blob/master/lovelace/modified-custom-cards/nest-layout-card.js

@marrobHD  is this what You are looking for? 🙂
