### ISSUE TITLE
Missing resources.yaml

### ISSUE THREAD

**Issue by facos86** [isabellaalstrom/home-assistant-config#5]
Hi !
It seems there is a missing file, in ui-lovelace.yaml, there is a include to resources.yaml bu i can't find the file anywhere in the repo
https://github.com/isabellaalstrom/home-assistant-config/blob/0f07b8050baa9d936b6b5da1fe740fa84419b49c/ui-lovelace.yaml#L2

**Comment by sybux** [comment]
Hi,
also looking for this file. It seems that it's part of main system to load every js file.
Actually I'm getting the following error :

> Custom element doesn't exist: nest-layout-card.
> type: 'custom:nest-layout-card'

but I can find where to map the nest-layout-card.js to load this feature.
